package com.ping.pingword.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CHALLENGE".
 */
public class Challenge implements java.io.Serializable {

    private Long id;
    private Integer rightNum;
    private Integer rank;
    private Integer position;

    public Challenge() {
    }

    public Challenge(Long id) {
        this.id = id;
    }

    public Challenge(Long id, Integer rightNum, Integer rank, Integer position) {
        this.id = id;
        this.rightNum = rightNum;
        this.rank = rank;
        this.position = position;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getRightNum() {
        return rightNum;
    }

    public void setRightNum(Integer rightNum) {
        this.rightNum = rightNum;
    }

    public Integer getRank() {
        return rank;
    }

    public void setRank(Integer rank) {
        this.rank = rank;
    }

    public Integer getPosition() {
        return position;
    }

    public void setPosition(Integer position) {
        this.position = position;
    }

}
